version: '3.8'

services:
  app:
    restart: always
    container_name: nest-site
    build:
      context: .
      dockerfile: Dockerfile
      no_cache: true
    ports:
      - '3005:3000'
    environment:
      - AUTH_SECRET=x4gwbtf6te5qs94ru1532ns0nrr602t6jvc4ursrniu5mbs3jzqh5ncli0ponz45
      - DATABASE_URL=file:/app/db/prod.db
    volumes:
      - ./data/db:/app/db
      - ./data/logs:/app/logs
      - ./data/upload:/app/static/upload
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
